using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MinimalActorSystem.SourceGenerator;

/// <summary>
/// Source generator для автоматической генерации диспетчеризации писем в акторах.
/// Ищет partial-классы с атрибутом <see cref="ActorLetterHandlerAttribute"/>,
/// находит private-методы вида On{TypeName}({TypeName} letter) и генерирует
/// переопределение OnLetter со switch по всем найденным типам.
/// </summary>
/// <remarks>
/// Source generator that automatically generates message dispatch in actors.
/// Looks for partial classes with <see cref="ActorLetterHandlerAttribute"/>,
/// finds private methods like On{TypeName}({TypeName} letter), and generates
/// an OnLetter override with a switch over all found letter types.
/// </remarks>
[Generator]
public class ActorLetterHandlerGenerator : ISourceGenerator
{
    private readonly HashSet<string> _generated = [];

    /// <inheritdoc/>
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
    }

    /// <inheritdoc/>
    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxContextReceiver is not SyntaxReceiver receiver)
            return;

        foreach (ClassDeclarationSyntax classDecl in receiver.Candidates)
        {
            SemanticModel model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
                continue;

            var handlers = new List<(string TypeName, string MethodName)>();

            foreach (ISymbol member in classSymbol.GetMembers())
            {
                if (member is not IMethodSymbol method)
                    continue;
                if (method.DeclaredAccessibility != Accessibility.Private)
                    continue;
                if (method.ReturnType.ToString() != "System.Threading.Tasks.ValueTask")
                    continue;
                if (method.Parameters.Length != 1)
                    continue;

                ITypeSymbol paramType = method.Parameters[0].Type;
                if (paramType is not INamedTypeSymbol namedType)
                    continue;
                if (!namedType.IsSealed)
                    continue;
                if (!InheritsFromLetter(namedType))
                    continue;

                var expectedName = $"On{namedType.Name}";
                if (method.Name != expectedName)
                    continue;

                handlers.Add((namedType.Name, method.Name));
            }

            if (!_generated.Add(classSymbol.ToDisplayString()))
                continue;

            if (handlers.Count == 0)
                continue;

            var source = GenerateSource(classSymbol, handlers);
            context.AddSource($"{classSymbol.Name}.OnLetter.g.cs", source);
        }
    }

    /// <summary>
    /// Проверяет, наследуется ли указанный тип от Letter.
    /// </summary>
    /// <param name="type">Тип для проверки.</param>
    /// <returns>true, если тип наследуется от Letter; иначе false.</returns>
    /// <remarks>
    /// Checks whether the specified type inherits from Letter.
    /// </remarks>
    private static bool InheritsFromLetter(INamedTypeSymbol type)
    {
        INamedTypeSymbol baseType = type.BaseType;
        while (baseType != null)
        {
            if (baseType.ToDisplayString() == "MinimalActorSystem.Letter")
                return true;
            baseType = baseType.BaseType;
        }
        return false;
    }

    /// <summary>
    /// Генерирует исходный код для переопределения OnLetter.
    /// </summary>
    /// <param name="classSymbol">Символ класса, для которого генерируется код.</param>
    /// <param name="handlers">Список пар (имя типа письма, имя метода-обработчика).</param>
    /// <returns>Сгенерированный исходный код.</returns>
    /// <remarks>
    /// Generates source code for the OnLetter override.
    /// </remarks>
    private static string GenerateSource(INamedTypeSymbol classSymbol, List<(string TypeName, string MethodName)> handlers)
    {
        var sb = new StringBuilder(1024);
        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();
        var indent = namespaceName != null ? "    " : "";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS8019");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using MinimalActorSystem;");
        sb.AppendLine();

        if (namespaceName != null)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"{indent}public partial class {classSymbol.Name}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    protected override ValueTask OnLetter(Letter letter)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        switch (letter)");
        sb.AppendLine($"{indent}        {{");

        foreach ((string typeName, string methodName) in handlers)
        {
            sb.AppendLine($"{indent}            case {typeName} msg:");
            sb.AppendLine($"{indent}                return {methodName}(msg);");
        }

        sb.AppendLine($"{indent}            default:");
        sb.AppendLine($"{indent}                return default;");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}}");

        return sb.ToString();
    }

    /// <summary>
    /// Синтаксический ресивер для сбора кандидатов на генерацию кода.
    /// Находит partial-классы с атрибутом ActorLetterHandler.
    /// </summary>
    /// <remarks>
    /// Syntax receiver that collects candidates for code generation.
    /// Finds partial classes with the ActorLetterHandler attribute.
    /// </remarks>
    private class SyntaxReceiver : ISyntaxContextReceiver
    {
        /// <summary>
        /// Список классов-кандидатов, для которых будет выполнена генерация.
        /// </summary>
        public List<ClassDeclarationSyntax> Candidates { get; } = [];

        /// <inheritdoc/>
        public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
        {
            if (context.Node is not ClassDeclarationSyntax classDecl)
                return;

            // Класс должен быть partial
            if (!classDecl.Modifiers.Any(SyntaxKind.PartialKeyword))
                return;

            // Класс должен иметь атрибут ActorLetterHandler
            var hasAttribute = classDecl.AttributeLists
                .SelectMany(al => al.Attributes)
                .Any(attr => attr.Name.ToString() == "ActorLetterHandler"
                          || attr.Name.ToString() == "ActorLetterHandlerAttribute");

            if (!hasAttribute)
                return;

            Candidates.Add(classDecl);
        }
    }
}
