using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MinimalActorSystem.SourceGenerator;

[Generator]
public class ActorLetterHandlerGenerator : ISourceGenerator
{
    private readonly HashSet<string> _generated = new();

    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxContextReceiver is not SyntaxReceiver receiver)
            return;

        foreach (var classDecl in receiver.Candidates)
        {
            var model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
            var classSymbol = model.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            if (classSymbol == null)
                continue;

            var handlers = new List<(string TypeName, string MethodName)>();

            foreach (var member in classSymbol.GetMembers())
            {
                if (member is not IMethodSymbol method)
                    continue;
                if (method.DeclaredAccessibility != Accessibility.Private)
                    continue;
                if (method.ReturnType.ToString() != "System.Threading.Tasks.ValueTask")
                    continue;
                if (method.Parameters.Length != 1)
                    continue;

                var paramType = method.Parameters[0].Type;
                if (paramType is not INamedTypeSymbol namedType)
                    continue;
                if (!namedType.IsSealed)
                    continue;
                if (!InheritsFromLetter(namedType))
                    continue;

                var expectedName = $"On{namedType.Name}";
                if (method.Name != expectedName)
                    continue;

                handlers.Add((namedType.Name, method.Name));
            }

            if (!_generated.Add(classSymbol.ToDisplayString()))
                continue;

            if (handlers.Count == 0)
                continue;

            var source = GenerateSource(classSymbol, handlers);
            context.AddSource($"{classSymbol.Name}.OnLetter.g.cs", source);
        }
    }

    private static bool InheritsFromLetter(INamedTypeSymbol type)
    {
        var baseType = type.BaseType;
        while (baseType != null)
        {
            if (baseType.ToDisplayString() == "MinimalActorSystem.Letter")
                return true;
            baseType = baseType.BaseType;
        }
        return false;
    }

    private static string GenerateSource(INamedTypeSymbol classSymbol, List<(string TypeName, string MethodName)> handlers)
    {
        var sb = new StringBuilder();
        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();
        var indent = namespaceName != null ? "    " : "";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS8019");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using MinimalActorSystem;");
        sb.AppendLine();

        if (namespaceName != null)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"{indent}public partial class {classSymbol.Name}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    protected override ValueTask OnLetter(Letter letter)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        switch (letter)");
        sb.AppendLine($"{indent}        {{");

        foreach (var (typeName, methodName) in handlers)
        {
            sb.AppendLine($"{indent}            case {typeName} msg:");
            sb.AppendLine($"{indent}                return {methodName}(msg);");
        }

        sb.AppendLine($"{indent}            default:");
        sb.AppendLine($"{indent}                return default;");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}}");

        return sb.ToString();
    }

    private class SyntaxReceiver : ISyntaxContextReceiver
    {
        public List<ClassDeclarationSyntax> Candidates { get; } = new();

        public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
        {
            if (context.Node is not ClassDeclarationSyntax classDecl)
                return;

            if (!classDecl.Modifiers.Any(SyntaxKind.PartialKeyword))
                return;

            var hasAttribute = classDecl.AttributeLists
                .SelectMany(al => al.Attributes)
                .Any(attr => attr.Name.ToString() == "ActorLetterHandler"
                          || attr.Name.ToString() == "ActorLetterHandlerAttribute");

            if (!hasAttribute)
                return;

            Candidates.Add(classDecl);
        }
    }
}
