<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<LangVersion>12.0</LangVersion>
		<Nullable>enable</Nullable>
		<NoWarn>$(NoWarn);IDE0130</NoWarn>

		<!-- Метаданные пакета -->
		<PackageId>MinimalActorSystem</PackageId>
		<Version>1.0.2</Version>
		<Authors>Сергей Гурин</Authors>
		<Description>Минималистичная акторная система на C#. Изолированные акторы, обмен сообщениями, виртуальное время для тестов.</Description>
		<PackageTags>actors;actor-model;concurrency;messaging;testing</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<!-- Подключение README.md в пакет -->
	<PropertyGroup>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
	  <PackageReference Include="System.Threading.Channels" Version="10.0.7" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="System" />
		<Using Include="System.Collections.Generic" />
		<Using Include="System.Threading" />
		<Using Include="System.Threading.Tasks" />
		<Using Include="System.Threading.Channels" />
		<Using Include="Microsoft.Extensions.Logging" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>MinimalActorSystem.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
	
</Project>
