<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<LangVersion>12.0</LangVersion>
		<Nullable>enable</Nullable>
		<NoWarn>$(NoWarn);IDE0130</NoWarn>
		<Version>1.0.6</Version>
		<Authors>Сергей Гурин, Россия, Томск. SERGEY GURIN, RUSSIA, TOMSK</Authors>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="System" />
		<Using Include="System.Collections.Generic" />
		<Using Include="System.Threading" />
		<Using Include="System.Threading.Tasks" />
		<Using Include="Microsoft.Extensions.Logging" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>MinimalActorSystem.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\MinimalActorSystem\MinimalActorSystem.csproj" />
	</ItemGroup>

</Project>
