services:
  benchmarks:
    build:
      context: .
      dockerfile: Dockerfile
    image: minimal-actor-system-benchmarks
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
    depends_on:
      - collector

  collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"